// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  about_us_header_area: dynamic(() => import('./AboutUsHeaderArea')),
  birthday_gift: dynamic(() => import('./BirthdayGift')),
  chose_designs: dynamic(() => import('./ChooseDesigns')),
  e_club_header: dynamic(() => import('./EClubHeader')),
  form: dynamic(() => import('./Form')),
  franchising_about_section: dynamic(() => import('./FranchisingAboutSection')),
  franchising_get_started_section: dynamic(() => import('./FranchisingGetStartedSection')),
  franchising_header: dynamic(() => import('./FranchisingHeader')),
  franchising_how_to: dynamic(() => import('./FranchisingHowTo')),
  franchising_menu_section: dynamic(() => import('./FranchisingMenuSection')),
  franchising_purpose_section: dynamic(() => import('./FranchisingPurposeSection')),
  gift_cards_header: dynamic(() => import('./GiftCardsHeader')),
  home_e_club: dynamic(() => import('./HomeEClub')),
  home_gallery: dynamic(() => import('./HomeGallery')),
  home_header: dynamic(() => import('./HomeHeader')),
  home_info_section: dynamic(() => import('./HomeInfoSection')),
  how_does_it_work: dynamic(() => import('./HowDoesItWork')),
  how_it_started: dynamic(() => import('./HowItStarted')),
  lets_connect: dynamic(() => import('./LetsConnect')),
  menu_left_aligned_item: dynamic(() => import('./MenuItem')),
  navigation_list: dynamic(() => import('./NavigationList')),
  text_block: dynamic(() => import('./MenuHeader')),
};
