// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  home_header: dynamic(() => import('./HomeHeader')),
  home_info_section: dynamic(() => import('./HomeInfoSection')),
  navigation_list: dynamic(() => import('./NavigationList')),
};
